# Generated by Django 5.1.5 on 2025-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nexususer',
            old_name='access_token',
            new_name='apple_access_token',
        ),
        migrations.RenameField(
            model_name='nexususer',
            old_name='refresh_token',
            new_name='apple_refresh_token',
        ),
        migrations.RenameField(
            model_name='nexususer',
            old_name='apple_sub',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='nexususer',
            name='nexus_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nexususer',
            name='nexus_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nexususer',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
