# Generated by Django 5.1.6 on 2025-02-12 03:47

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexususer',
            name='profile_image',
            field=models.ImageField(default='user_profile_images/default.jpg', upload_to=accounts.utils.get_NexusUser_profile_image_upload_path),
        ),
    ]
