# Generated by Django 5.1.5 on 2025-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_access_token_nexususer_apple_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexususer',
            name='user_name',
            field=models.CharField(default='Anonymous_user', max_length=255),
        ),
    ]
