# Generated by Django 5.1.5 on 2025-02-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_nexususer_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nexususer',
            name='nexus_access_token',
        ),
        migrations.RemoveField(
            model_name='nexususer',
            name='nexus_refresh_token',
        ),
    ]
