# Generated by Django 5.1.6 on 2025-02-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_nexususer_profile_image'),
        ('engine', '0007_remove_nexusfile_likes_alter_nexusfile_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexususer',
            name='liked_files',
            field=models.ManyToManyField(related_name='like_users', to='engine.nexusfile'),
        ),
    ]
