# Generated by Django 5.1.6 on 2025-02-25 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_nexususer_liked_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nexususer',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='nexususer',
            name='apple_access_token',
        ),
        migrations.RemoveField(
            model_name='nexususer',
            name='apple_refresh_token',
        ),
        migrations.RemoveField(
            model_name='nexususer',
            name='user_name',
        ),
        migrations.AddField(
            model_name='nexususer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nexususer',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='nexususer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='nexususer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
