# Generated by Django 5.1.6 on 2025-03-04 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_id_nexususer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nexususer',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
