# Generated by Django 5.1.6 on 2025-03-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_nexususer_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nexususer',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
