# Generated by Django 5.1.6 on 2025-03-05 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_nexususer_last_login'),
        ('engine', '0008_alter_nexusfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexususer',
            name='banned_files',
            field=models.ManyToManyField(related_name='ban_users', to='engine.nexusfile'),
        ),
        migrations.CreateModel(
            name='NexusUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('F', 'follow'), ('B', 'block')], max_length=10)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nexususer',
            name='relations',
            field=models.ManyToManyField(related_name='+', through='accounts.NexusUserRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='nexususerrelation',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user', 'relation_type'), name='unique_relation'),
        ),
    ]
