# Generated by Django 5.1.6 on 2025-03-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_nexususer_banned_files_and_more'),
        ('engine', '0008_alter_nexusfile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nexususer',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='nexususer',
            name='disliked_files',
            field=models.ManyToManyField(related_name='dislike_users', to='engine.nexusfile'),
        ),
        migrations.AlterField(
            model_name='nexususerrelation',
            name='relation_type',
            field=models.CharField(choices=[('F', 'follow'), ('B', 'block'), ('R', 'report')], max_length=10),
        ),
    ]
