# Generated by Django 5.1.6 on 2025-02-12 12:39

import engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nexusfile',
            options={},
        ),
        migrations.RemoveField(
            model_name='nexusfile',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='nexusfile',
            name='name',
        ),
        migrations.AddField(
            model_name='nexusfile',
            name='model_file',
            field=models.FileField(default='nexus_models/default_profile.jpg', upload_to=engine.models.get_NexusFile_upload_path),
        ),
    ]
