# Generated by Django 5.1.6 on 2025-02-12 12:40

import engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_nexusfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nexusfile',
            name='model_file',
            field=models.FileField(upload_to=engine.models.get_NexusFile_upload_path),
        ),
    ]
