# Generated by Django 5.1.6 on 2025-02-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_nexusfile_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexusfile',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
