# Generated by Django 5.1.6 on 2025-02-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_nexusfile_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nexusfile',
            old_name='like_count',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='nexusfile',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
