# Generated by Django 5.1.6 on 2025-02-13 09:04

import engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_rename_like_count_nexusfile_likes_nexusfile_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nexusfile',
            options={'ordering': ['views']},
        ),
        migrations.AlterField(
            model_name='nexusfile',
            name='model_file',
            field=models.FileField(unique=True, upload_to=engine.models.get_NexusFile_upload_path),
        ),
    ]
