# Generated by Django 5.1.6 on 2025-02-14 02:09

import engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_alter_nexusfile_options_alter_nexusfile_model_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nexusfile',
            name='likes',
        ),
        migrations.AlterField(
            model_name='nexusfile',
            name='model_file',
            field=models.FileField(upload_to=engine.models.get_NexusFile_upload_path),
        ),
    ]
