# Generated by Django 5.1.6 on 2025-02-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_remove_nexusfile_likes_alter_nexusfile_model_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nexusfile',
            options={'ordering': ['-views']},
        ),
    ]
