# Generated by Django 5.1.6 on 2025-03-06 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_alter_nexusfile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nexusfile',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nexusfile',
            name='disliked_users',
            field=models.ManyToManyField(related_name='disliked_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nexusfile',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
