# Generated by Django 5.1.6 on 2025-03-08 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_nexusfile_blocked_users_nexusfile_disliked_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nexusfile',
            name='reported_users',
            field=models.ManyToManyField(related_name='reported_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
