# Generated by Django 5.1.6 on 2025-03-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_nexusfile_reported_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexusfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nexusfile',
            name='title',
            field=models.CharField(default='default title', max_length=255),
            preserve_default=False,
        ),
    ]
