# Generated by Django 5.1.6 on 2025-03-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_nexusfile_description_nexusfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nexusfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
